curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.M
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.L
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.ML
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.S
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.assoc
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.china_taiwan
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.edict
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.fullname
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.geo
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.hukugougo
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.itaiji
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.jinmei
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.law
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.lisp
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.mazegaki
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.noregist
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.not_wrong
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.notes
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.okinawa
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.propernoun
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.pubdic+
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.requested
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.station
curl -O http://openlab.ring.gr.jp/skk/skk/dic/SKK-JISYO.wrong.annotated
